### ISSUE TITLE
Read file by `for line in f`

### ISSUE THREAD

**Issue by stegben** [scarletcho/KoLM#3]
Some of the code like [this](https://github.com/scarletcho/KoLM/blob/master/kolm/g2p.py#L57) can be optimized by:
```python
# instead of
# while True:
#     f.readline()
for line in f:
    ... 
```
It's both faster and easier to read. You may reference to [this post](http://stackoverflow.com/a/8010133) for more detail.

**Comment by scarletcho** [comment]
Thanks!
